const CARDS = { # Rank, Suit
	# HEARTS
	"AH" : [1,"Hearts"],
	"2H" : [2,"Hearts"],
	"3H" : [3,"Hearts"],
	"4H" : [4,"Hearts"],
	"5H" : [5,"Hearts"],
	"6H" : [6,"Hearts"],
	"7H" : [7,"Hearts"],
	"8H" : [8,"Hearts"],
	"9H" : [9,"Hearts"],
	"10H" : [10,"Hearts"],
	"JH" : [11,"Hearts"],
	"QH" : [12,"Hearts"],
	"KH" : [13,"Hearts"],
	# DIAMONDS
	"AD" : [1,"Diamonds"],
	"2D" : [2,"Diamonds"],
	"3D" : [3,"Diamonds"],
	"4D" : [4,"Diamonds"],
	"5D" : [5,"Diamonds"],
	"6D" : [6,"Diamonds"],
	"7D" : [7,"Diamonds"],
	"8D" : [8,"Diamonds"],
	"9D" : [9,"Diamonds"],
	"10D" : [10,"Diamonds"],
	"JD" : [11,"Diamonds"],
	"QD" : [12,"Diamonds"],
	"KD" : [13,"Diamonds"],
	# CLUBS
	"AC" : [1,"Clubs"],
	"2C" : [2,"Clubs"],
	"3C" : [3,"Clubs"],
	"4C" : [4,"Clubs"],
	"5C" : [5,"Clubs"],
	"6C" : [6,"Clubs"],
	"7C" : [7,"Clubs"],
	"8C" : [8,"Clubs"],
	"9C" : [9,"Clubs"],
	"10C" : [10,"Clubs"],
	"JC" : [11,"Clubs"],
	"QC" : [12,"Clubs"],
	"KC" : [13,"Clubs"],
	# SPADES
	"AS" : [1,"Spades"],
	"2S" : [2,"Spades"],
	"3S" : [3,"Spades"],
	"4S" : [4,"Spades"],
	"5S" : [5,"Spades"],
	"6S" : [6,"Spades"],
	"7S" : [7,"Spades"],
	"8S" : [8,"Spades"],
	"9S" : [9,"Spades"],
	"10S" : [10,"Spades"],
	"JS" : [11,"Spades"],
	"QS" : [12,"Spades"],
	"KS" : [13,"Spades"]
}
